development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:1b020e53b0ed516b09a07483974fcef5@scat.redistogo.com:10411/
  channel_prefix: message_me_production
